type: rand([1,2,3]);
/*type 1 has a fractional power, 2 is factored poly, 3 is expanded poly*/

pow: if type = 1 then rand([[8,9], [5,6], [6,7], [7,8]])
 else makelist(rand([1,2,3,4]), 2);
coef: makelist(rand([1,2,3,4,5]), 3);

arg: if type = 1 then x^(pow[2]/pow[1])
 else (x^pow[1]+coef[1])*(coef[2]*x^pow[2]+coef[3]);
disparg: if type = 3 then expand(arg) else arg;
defint: integrate(disparg, x);
tans: defint + C;