[var1,var2]:rand([[x,y],[y,x]]);/*rotated about the var1-axis*/
coeffs:append([3,rand(4)+2],rand_selection(makelist(i^2-4,i,2,6),2));
[coeffs[3],coeffs[4]]:[min(coeffs[3],coeffs[4]),max(coeffs[3],coeffs[4])];
[type,equation]:rand([[0,var1=1/coeffs[1]*var2^(3/2)],[1,var1=coeffs[1]+coeffs[2]*var2^2]]);
func:rhs(equation);
dvar1dvar2:diff(func,var2);
integrand:2*%pi*var2*sqrt(1+dvar1dvar2^2);
tans1:integrate(integrand,var2,coeffs[3],coeffs[4]);