depends(y,x);
A1: rand([1,2,3,4,5]);
A2: rand([1,2,3,4,5]);
A3: -rand([1,2,3,4,5]);
ode: A1*diff(y,x,2)+A2*diff(y,x)+A3*y=0;
kval1: (-A2+sqrt(A2^2-4*A1*A3))/(2*A1);
kval2: (-A2-sqrt(A2^2-4*A1*A3))/(2*A1);
sol1: exp(k*x);
genfn: A*exp(k_1*x)+B*exp(k_2*x);
gendv1: diff(genfn,x);
gendv2: diff(genfn,x,2);

tans1: ratsimp({kval1,kval2});
tans2: gendv2;
tans3: A1*k_1^2+A2*k_1+A3;
tans4: B*exp(k_2*x);
tans5: A1;