r():= rand_with_prohib(-5, 5, [0]);
m: apply( matrix, 
    random_permutation(
        [
            [r(),   r(), r()],
            [r(), 0,   r()],
            [r(), r(), 0  ]
        ]
    )
);

make_eqn(row_, rhs_):= row_[1] * x + row_[2] * y + row_[3] * z = rhs_;

eqn_1: make_eqn(m[1], r());
eqn_2: make_eqn(m[2], r());
eqn_3: make_eqn(m[3], r());

tans1: addcol(m,[rhs(eqn_1), rhs(eqn_2), rhs(eqn_3)]);