vectorify(list):=sconcat("⟨",list[1],",",list[2],",",list[3],"⟩");

vectors:makelist(makelist(rand_with_prohib(-5,5,[0]),3),3);
Pcoor:makelist(rand_with_prohib(-5,5,[0]),3);

if(is(determinant(matrix(vectors[1],vectors[2],vectors[3]))=0))
then vectors:[[4,2,-3],[1,1,2],[5,-3,4]];

[Qcoor,Rcoor,Scoor]:makelist(Pcoor+vectors[i],i,3);

tans1:abs(determinant(matrix(vectors[1],vectors[2],vectors[3])));