vectorify(list):=sconcat("⟨",list[1],",",list[2],",",list[3],"⟩");

vectors:makelist(makelist(rand_with_prohib(-5,5,[0]),3),2);
Pcoor:makelist(rand_with_prohib(-5,5,[0]),3);

crossProduct(a,b) := [a[2]*b[3]-a[3]*b[2],a[3]*b[1]-a[1]*b[3],a[1]*b[2]-a[2]*b[1]];

if(is(crossProduct(vectors[1],vectors[2])=[0,0,0]))
then vectors:[[4,2,-3],[1,1,2]];

[Qcoor,Rcoor]:makelist(Pcoor+vectors[i],i,2);

tans1:crossProduct(vectors[1],vectors[2]);
tans2:sqrt(tans1[1]^2+tans1[2]^2+tans1[3]^2)/2;